export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ADS_ROUTE = '/ads'
export const MYADS_ROUTE = '/myAds'
export const CHAT_ROUTE = '/chat'
export const PROFILE_ROUTE = '/profile'
